version: "3.8"

services:

        eureka:
                build: ./server/
                image: eureka-server:0.1
                container_name: eureka
                ports:
                        - "8761:8761"
                networks:
                        - micro_network

        gateway:
                build: ./gateway/
                image: gateway-server:0.1
                container_name: gateway
                depends_on:
                        eureka:
                                condition: service_started
                links:
                        - eureka
                ports:
                        - "8180:8180"
                networks:
                        - micro_network

        readsensor:
                build: ./readsensor/
                image: readsensor:0.1
                container_name: readsensor
                ports:
                        - "8380:8380"
                depends_on:
                        eureka:
                                condition: service_started
                        gateway:
                                condition: service_started

                links:
                        - eureka
                        - gateway
                volumes:
                        - /opt/docker/log:/app/log
                networks:
                        - micro_network

        sensorsave:
                build: ./sensorsave/
                image: sensorsave:0.1
                container_name: sensorsave
                ports:
                        - "8480:8480"
                depends_on:
                        eureka:
                                condition: service_started
                        gateway:
                                condition: service_started
                links:
                        - eureka
                        - gateway
                volumes:
                        - /opt/docker/log:/app/log
                networks:
                        - micro_network

        client:
                build: ./clients/
                image: clients:0.1
                container_name: clients
                ports:
                        - "8580:8580"
                depends_on:
                        eureka:
                                condition: service_started
                        gateway:
                                condition: service_started
                links:
                        - eureka
                        - gateway
                volumes:
                        - /opt/docker/log:/app/log
                networks:
                        - micro_network

networks:
        micro_network:
                driver: bridge  
