
spring:
  application:
    name: sensor-save-ms
  rabbitmq:
    host: ${HOST_MQ}
    virtual-host: ${VIRTUAL_HOST_MQ}
    port: ${PORT_MQ}
    username: ${USERNAME_MQ}
    password: ${PASSWORD_MQ}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}?retryWrites=true&w=majority
      database: ${MONGO_DATABASE}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

mq:
  queues:
    dados-sensores: dados-sensores