spring:
  application:
    name: clients-ms

  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.jjvyex7.mongodb.net/?retryWrites=true&w=majority
      database: climateDb

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
