spring:
  application:
    name: clients-ms

  data:
    mongodb:
      uri: mongodb://root:root@MONGOAPPL:27017/climateDb?retryWrites=true&w=majority
      database: climateDb

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
